---
- name: Install and run apache
  hosts: ubuntuservers
  become: true
  tasks:
    - name: Install service
      ansible.builtin.apt:
        name: apache2
        state: latest
    - name: Create content
      template:
        src: index.html
        dest: /var/www/html/index.html
    - name: Run service
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: yes